"""Create Medication x Schedule association

Revision ID: 243c27ed8eb8
Revises: 58fb4a7ad2d1
Create Date: 2025-01-11 22:43:59.840267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243c27ed8eb8'
down_revision: Union[str, None] = '58fb4a7ad2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_schedule_association',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('medication_id', sa.String(), nullable=True),
                    sa.Column('schedule_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['medication_id'], ['medications.id'], ),
                    sa.ForeignKeyConstraint(
                        ['schedule_id'], ['medication_schedules.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_medication_schedule_association_id'),
                    'medication_schedule_association', ['id'], unique=False)
    op.drop_constraint('medication_schedules_medication_id_fkey',
                       'medication_schedules', type_='foreignkey')
    op.drop_column('medication_schedules', 'medication_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_schedules', sa.Column(
        'medication_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('medication_schedules_medication_id_fkey',
                          'medication_schedules', 'medications', ['medication_id'], ['id'])
    op.drop_index(op.f('ix_medication_schedule_association_id'),
                  table_name='medication_schedule_association')
    op.drop_table('medication_schedule_association')
    # ### end Alembic commands ###
