"""Refactor Medication table, user and medication schedule creation

Revision ID: 58fb4a7ad2d1
Revises: e185b7288abc
Create Date: 2025-01-11 19:58:43.863095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58fb4a7ad2d1'
down_revision: Union[str, None] = 'e185b7288abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('nickname', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )

    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users',
                    ['nickname'], unique=False)

    op.create_table('medication_schedules',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('medication_id', sa.String(), nullable=True),
                    sa.Column('schedule_time', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['medication_id'], ['medications.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_medication_schedules_id'),
                    'medication_schedules', ['id'], unique=False)
    op.create_table('user_medications',
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('medication_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['medication_id'], ['medications.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'medication_id')
                    )
    op.drop_column('medications', 'schedule_times')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('schedule_times', postgresql.ARRAY(
        sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_table('user_medications')
    op.drop_index(op.f('ix_medication_schedules_id'),
                  table_name='medication_schedules')
    op.drop_table('medication_schedules')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
